# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\wow_addon_backup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(475, 176)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonAddonBackup = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_backup())
        self.buttonAddonBackup.setGeometry(QtCore.QRect(350, 110, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonAddonBackup.setFont(font)
        self.buttonAddonBackup.setObjectName("buttonAddonBackup")
        self.lineBackupDir = QtWidgets.QLineEdit(self.centralwidget)
        self.lineBackupDir.setGeometry(QtCore.QRect(90, 30, 311, 21))
        self.lineBackupDir.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lineBackupDir.setClearButtonEnabled(False)
        self.lineBackupDir.setObjectName("lineBackupDir")
        self.lineBackupLocationDir = QtWidgets.QLineEdit(self.centralwidget)
        self.lineBackupLocationDir.setGeometry(QtCore.QRect(90, 60, 311, 21))
        self.lineBackupLocationDir.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lineBackupLocationDir.setClearButtonEnabled(False)
        self.lineBackupLocationDir.setObjectName("lineBackupLocationDir")
        self.labelAddonDir = QtWidgets.QLabel(self.centralwidget)
        self.labelAddonDir.setGeometry(QtCore.QRect(0, 30, 71, 21))
        self.labelAddonDir.setObjectName("labelAddonDir")
        self.labelBackupDir = QtWidgets.QLabel(self.centralwidget)
        self.labelBackupDir.setGeometry(QtCore.QRect(0, 60, 81, 21))
        self.labelBackupDir.setObjectName("labelBackupDir")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 475, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WoW AddOn Backup"))
        self.buttonAddonBackup.setText(_translate("MainWindow", "Backup AddOns"))
        self.lineBackupDir.setText(_translate("MainWindow", " C:\\World of Warcraft\\_retail_\\Interface\\AddOns"))
        self.lineBackupLocationDir.setText(_translate("MainWindow", " C:\\My Backups\\AddOns"))
        self.labelAddonDir.setText(_translate("MainWindow", "Addon Dir:"))
        self.labelBackupDir.setText(_translate("MainWindow", "Backup Location:"))

    def press_backup(self):
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        self.labelAddonDir.setText("HUGE PENIS!")
        self.labelAddonDir.setFont(font)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
