# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\wow_addon_backup.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os, zipfile


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(475, 176)
        MainWindow.setAutoFillBackground(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.buttonAddonBackup = QtWidgets.QPushButton(self.centralwidget, clicked=lambda: self.press_backup(self.lineBackupDir.text()))
        self.buttonAddonBackup.setGeometry(QtCore.QRect(350, 110, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.buttonAddonBackup.setFont(font)
        self.buttonAddonBackup.setObjectName("buttonAddonBackup")
        self.lineBackupDir = QtWidgets.QLineEdit(self.centralwidget)
        self.lineBackupDir.setGeometry(QtCore.QRect(90, 30, 311, 21))
        self.lineBackupDir.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lineBackupDir.setClearButtonEnabled(False)
        self.lineBackupDir.setObjectName("lineBackupDir")
        self.lineBackupLocationDir = QtWidgets.QLineEdit(self.centralwidget)
        self.lineBackupLocationDir.setGeometry(QtCore.QRect(90, 60, 311, 21))
        self.lineBackupLocationDir.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.lineBackupLocationDir.setClearButtonEnabled(False)
        self.lineBackupLocationDir.setObjectName("lineBackupLocationDir")
        self.labelAddonDir = QtWidgets.QLabel(self.centralwidget)
        self.labelAddonDir.setGeometry(QtCore.QRect(0, 30, 71, 21))
        self.labelAddonDir.setObjectName("labelAddonDir")
        self.labelBackupDir = QtWidgets.QLabel(self.centralwidget)
        self.labelBackupDir.setGeometry(QtCore.QRect(0, 60, 81, 21))
        self.labelBackupDir.setObjectName("labelBackupDir")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(410, 30, 25, 19))
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton_2.setGeometry(QtCore.QRect(410, 60, 25, 19))
        self.toolButton_2.setObjectName("toolButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 475, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WoW AddOn Backup"))
        self.buttonAddonBackup.setText(_translate("MainWindow", "Backup AddOns"))
        self.lineBackupDir.setText(_translate("MainWindow", r"C:\Program Files (x86)\World of Warcraft\_retail_\Interface\Addons"))
        self.lineBackupLocationDir.setText(_translate("MainWindow", "C:\\My Backups\\AddOns"))
        self.labelAddonDir.setText(_translate("MainWindow", "Addon Dir:"))
        self.labelBackupDir.setText(_translate("MainWindow", "Backup Location:"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.toolButton_2.setText(_translate("MainWindow", "..."))

    def press_backup(self, folder):
        # Backup the entire contents of "folder" into a ZIP file.

        folder = os.path.abspath(folder) # make sure folder is absolute

        # Figure out the filename this code should used based on
        # what files already exist.

        number = 1

        while True:
            zipFilename = os.path.basename(folder) + '_' + str(number) + '.zip'

            if not os.path.exists(zipFilename):
                break
            number = number + 1


        # Create the ZIP file.
        os.chdir(r'C:\Users\Gaming\Google Drive\Code\Python\Automate... book programs\ZipTests\booty')
        print(f'Creating {zipFilename}...')
        backupZip = zipfile.ZipFile(zipFilename, 'w')

        # Walk the entire folder tree and compress the files in each folder.

        # for foldername, subfolders, filenames in os.walk(os.path.relpath(folder)):
        for foldername, subfolders, filenames in os.walk(folder):
            print(f'Adding files in {foldername}...')

            # Add the current folder to the ZIP file.
            backupZip.write(foldername)

            # Add all the files in this folder to the ZIP file.
            for filename in filenames:
                if filename.startswith(os.path.basename(folder) + '_') and filename.endswith('.zip'):
                    continue # don't backup the backup ZIP files
                backupZip.write(os.path.join(foldername, filename))

        backupZip.close()
        print('Done.')


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
